services:

  vcard.api.gateway:
    image: ${DOCKER_REGISTRY-}vcardapigateway
    container_name: VCard.Api.Gateway
    build:
      context: .
      dockerfile: src/VCard.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8082
    ports:
      - 5002:8082
  
  vcard.users.api:
    image: ${DOCKER_REGISTRY-}vcardusersapi
    container_name: VCard.Users.Api
    build:
      context: .
      dockerfile: src/Services/Users/VCard.Users.Api/Dockerfile
    ports:
      - 5000:8080
  
  vcard.communication.api:
    image: ${DOCKER_REGISTRY-}vcardcommunicationapi
    container_name: VCard.Communication.Api
    build:
      context: .
      dockerfile: src/Services/Communication/VCard.Communication.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8083
    ports:
      - 5004:8083
  
  vcard.cards.api:
    image: ${DOCKER_REGISTRY-}vcardcardsapi
    container_name: VCard.Cards.Api
    build:
      context: .
      dockerfile: src/Services/Cards/VCard.Cards.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8084
    ports:
      - 5006:8084
  
  vcard.postgres.db:
    image: postgres
    container_name: VCard.Postgres.Db
    environment:
      POSTGRES_USER: vcard
      POSTGRES_PASSWORD: vcard
      POSTGRES_DB: vcard
    volumes:
      - ./containers/vcard.postgres.db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  vcard.rabbitmq:
    image: rabbitmq:management-alpine
    container_name: VCard.RabbitMQ
    hostname: vcard-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./containers/vcard.rabbitmq/data:/var/lib/rabbitmq
      - ./containers/vcard.rabbitmq/logs:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: vcard
      RABBITMQ_DEFAULT_PASS: vcard
      RABBITMQ_DEFAULT_VHOST: vcard
  
  consul:
    image: hashicorp/consul:latest
    container_name: VCard.Consul
    ports:
      - 8500:8500
    volumes:
      - ./containers/consul/data:/consul/data
  
  vcard.eventstoredb:
    image: eventstore/eventstore:24.2.0-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - 2113:2113
    volumes:
      - eventstore-volume-data:/var/lib/eventstore
      - eventstore-volume-logs:/var/log/eventstore
volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  