services:

  vcard.api.gateway:
    image: ${DOCKER_REGISTRY-}vcardapigateway
    container_name: VCard.Api.Gateway
    build:
      context: .
      dockerfile: src/VCard.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8082
    ports:
      - 5002:8082
      - 5003:8083
  
  vcard.users.api:
    image: ${DOCKER_REGISTRY-}vcardusersapi
    container_name: VCard.Users.Api
    build:
      context: .
      dockerfile: src/Services/Users/VCard.Users.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
  
  vcard.communication.api:
    image: ${DOCKER_REGISTRY-}vcardcommunicationapi
    container_name: VCard.Communication.Api
    build:
      context: .
      dockerfile: src/Services/Communication/VCard.Communication.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8083
    ports:
      - 5004:8084
      - 5005:8085
  
  vcard.postgres.db:
    image: postgres
    container_name: VCard.Postgres.Db
    environment:
      POSTGRES_USER: vcard
      POSTGRES_PASSWORD: vcard
      POSTGRES_DB: vcard
    volumes:
      - ./containers/vcard.postgres.db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432