# This is a generated file. Not intended for manual editing.
services:
  vcard.api.gateway:
    build:
      context: "D:\\c# learning\\VCard"
      dockerfile: "src/VCard.ApiGateway/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "vcardapigateway:dev"
    ports:
    - "127.0.0.1:57020:57100"
    - "127.0.0.1:57220:57300"
    volumes:
    - "C:\\Users\\albsz\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\c# learning\\VCard\\src\\VCard.ApiGateway:/app:rw"
    - "D:\\c# learning\\VCard:/src:rw"
    - "C:\\Users\\albsz\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.6\\\
      Linux64:/opt/rider-debugger"
    - "D:\\JetBrains Rider 2023.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\albsz\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_15_21_12_37:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  vcard.cards.api:
    build:
      context: "D:\\c# learning\\VCard"
      dockerfile: "src/Services/Cards/VCard.Cards.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "vcardcardsapi:dev"
    ports:
    - "127.0.0.1:57021:57100"
    - "127.0.0.1:57221:57300"
    volumes:
    - "C:\\Users\\albsz\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\c# learning\\VCard\\src\\Services\\Cards\\VCard.Cards.Api:/app:rw"
    - "D:\\c# learning\\VCard:/src:rw"
    - "C:\\Users\\albsz\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.6\\\
      Linux64:/opt/rider-debugger"
    - "D:\\JetBrains Rider 2023.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\albsz\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_15_21_12_37:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  vcard.communication.api:
    build:
      context: "D:\\c# learning\\VCard"
      dockerfile: "src/Services/Communication/VCard.Communication.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "vcardcommunicationapi:dev"
    ports:
    - "127.0.0.1:57022:57100"
    - "127.0.0.1:57222:57300"
    volumes:
    - "C:\\Users\\albsz\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\c# learning\\VCard\\src\\Services\\Communication\\VCard.Communication.Api:/app:rw"
    - "D:\\c# learning\\VCard:/src:rw"
    - "C:\\Users\\albsz\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.6\\\
      Linux64:/opt/rider-debugger"
    - "D:\\JetBrains Rider 2023.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\albsz\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_15_21_12_37:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  vcard.users.api:
    build:
      context: "D:\\c# learning\\VCard"
      dockerfile: "src/Services/Users/VCard.Users.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "vcardusersapi:dev"
    ports:
    - "127.0.0.1:57023:57100"
    - "127.0.0.1:57223:57300"
    volumes:
    - "C:\\Users\\albsz\\.nuget\\packages:/home/app/.nuget/packages"
    - "D:\\c# learning\\VCard\\src\\Services\\Users\\VCard.Users.Api:/app:rw"
    - "D:\\c# learning\\VCard:/src:rw"
    - "C:\\Users\\albsz\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.6\\\
      Linux64:/opt/rider-debugger"
    - "D:\\JetBrains Rider 2023.1\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\albsz\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_10_15_21_12_37:/var/opt/rider-debugger:rw"
    working_dir: "/app"
